name: dimension_predictions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=2.3.3
  - pandas=2.3.2
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - statsmodels=0.14.5
  - pytorch=2.7.0
  - torchvision=0.23.0
  - tqdm=4.67.1
  - pip:
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - Jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - MarkupSafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - packaging==25.0
      - patsy==1.0.1
      - pillow==11.3.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - PyYAML==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - SciencePlots==2.1.1
      - setuptools==80.9.0
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - transformers==4.56.2
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
